# # subprocess_run_output_error.py
#
# _____ ?
#
# ___
#     completed _ ?.r..
#         'echo to stdout; echo to s_e.. 1>&2; exit 1',
#         c.._T..
#         s.._T..
#         s_o__?.P..
#     )
# _____ ?.C.. __ err
#     print('ERROR:' ?
# ____
#     print('returncode:', ?.r_c..
#     print('Have @ bytes in stdout: @'.f..
#         le. ?.s_o_
#         ?.s_o_.d..'utf-8'
#
#
# # $ python3 subprocess_run_output_error.py
# #
# # to s_e..
# # ERROR: Command 'echo to stdout; echo to s_e.. 1>&2; exit 1'
# # returned non-zero exit status 1
